# SPDX-FileCopyrightText: no
# SPDX-License-Identifier: CC0-1.0
---
# Fedora display managers in priority order
displaymanagers:
  - sddm
  - lightdm
  - gdm
  - lxdm

defaultShowUsername:        true
basicSetup:                 true
sysconfig:                  false
