# SPDX-FileCopyrightText: no
# SPDX-License-Identifier: CC0-1.0
---
# grub2 configuration defaults for the installed system
overwrite: true
prefer_grub_d: false
keepDistributor: false

kernel_params: [ "quiet", "rhgb" ]

defaults:
    GRUB_DISTRIBUTOR: "Fedora Modern"
    GRUB_TIMEOUT: 5
    GRUB_DEFAULT: 0
    GRUB_DISABLE_SUBMENU: true
    GRUB_GFXMODE: "auto"
    GRUB_GFXPAYLOAD_LINUX: "keep"
    GRUB_DISABLE_RECOVERY: false
    GRUB_DISABLE_OS_PROBER: false
    GRUB_TERMINAL_OUTPUT: "gfxterm"

always_use_defaults: true
