# SPDX-FileCopyrightText: no
# SPDX-License-Identifier: CC0-1.0
---
# Use DNF as the package manager backend for Fedora
backend: dnf

skip_if_no_internet: false
update_db: false
update_system: false

operations:
  - remove:
    - calamares
    - calamares-libs
    - calamares-common
