# SPDX-FileCopyrightText: no
# SPDX-License-Identifier: CC0-1.0
---
efiSystemPartition:         "/boot/efi"
userSwapChoices:
    - none
    - small
    - suspend
    - reuse
drawNestedPartitions:       false
alwaysShowPartitionLabels:  true
initialPartitioningChoice:  none
initialSwapChoice:          none
defaultFileSystemType:      "ext4"
