import shutil
import subprocess
from pathlib import Path
from typing import Dict, Any

class KickstartManager:
    def __init__(self, config: Dict[str, Any]):
        self.config = config

    def _repos_section(self) -> str:
        res = ""
        repos = self.config.get("repos", [])
        for repo in repos:
            repo_id = repo.get("repo_id")
            metalink = repo.get("metalink")
            baseurl = repo.get("baseurl")
            if baseurl:
                res += f"repo --name={repo_id} --baseurl={baseurl}\n"
            elif metalink:
                res += f"repo --name={repo_id} --mirrorlist={metalink}\n"
        return res

    def _packages_section(self) -> str:
        res = "%packages\n"
        packages = self.config.get("packages", [])
        groups = self.config.get("groups", [])
        for g in groups:
            res += f"@{g}\n"
        for p in packages:
            res += f"{p}\n"
        res += "%end\n"
        return res

    def _post_section(self) -> str:
        res = "%post\n"
        services = self.config.get("services", [])
        for s in services:
            res += f"systemctl enable {s}\n"
        res += "%end\n"
        return res

    def generate(self) -> str:
        ks = "# auto-generated by fedora-builder\n"
        ks += "lang en_US.UTF-8\n"
        ks += "keyboard us\n"
        ks += "timezone UTC\n"
        ks += "rootpw --lock\n"
        
        live_user = self.config.get("live_user", "liveuser")
        groups = ",".join(self.config.get("live_groups", ["wheel"]))
        ks += f"user --name={live_user} --groups={groups} --password=live\n"
        
        selinux_mode = self.config.get("selinux_mode", "enforcing")
        ks += f"selinux --{selinux_mode}\n"
        
        ks += "firewall --enabled --service=ssh\n"
        
        ks += self._repos_section()
        ks += self._packages_section()
        ks += self._post_section()
        
        return ks

    def write(self, path: Path):
        with open(path, "w") as f:
            f.write(self.generate())

    def validate(self, ks_path: Path) -> bool:
        if shutil.which("ksvalidator"):
            res = subprocess.run(["ksvalidator", str(ks_path)])
            return res.returncode == 0
        return True
