# SPDX-FileCopyrightText: no
# SPDX-License-Identifier: CC0-1.0
# Calamares Main Settings - Fedora Modern
---
modules-search: [ local, /usr/lib/calamares/modules ]

instances:
  - id:       fedorasetup
    module:   shellprocess
    config:   shellprocess-fedorasetup.conf

sequence:
  - show:
    - welcome
    - locale
    - keyboard
    - partition
    - users
    - summary
  - exec:
    - partition
    - mount
    - unpackfs
    - fstab
    - locale
    - keyboard
    - localecfg
    - removeuser
    - users
    - displaymanager
    - networkcfg
    - hwclock
    - packages
    - services-systemd
    - grubcfg
    - bootloader
    - machineid
    - shellprocess@fedorasetup
    - umount
  - show:
    - finished

branding: fedora-modern
prompt-install: true
dont-chroot: false
oem-setup: false
disable-cancel: false
disable-cancel-during-exec: false
